# Dependencies
markdown:         redcarpet
pygments:         true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Permalinks
permalink:        pretty

# Setup
title:            odinserj
description:      'on development'
url:              http://odinserj.net
lang:             en

author:
  name:           'odinserj'
  url:            https://twitter.com/odinserj

paginate:         5

github:
  repo:           https://github.com/odinserj/odinserj.net

ga_tracking_id:   UA-49710849-1
ga_tracking_site: odinserj.net

disqus_short_name: odinserjnet
disqus_show_comment_count: true